### ISSUE TITLE
How to use it as Pipeline

### ISSUE THREAD

**Issue by chukkalapradeep** [jenkinsci/aws-sam-plugin#7]
Hi, Can you please suggest on how to use this plugin in the multipipe line.

**Comment by sulfasTor** [comment]
Hi, I felt into the same issue. Found this info [https://jenkins.io/doc/pipeline/steps/aws-sam/](url)  but the lack of examples keep me using the plugin with a Freestyle project

**Comment by man-bohara** [comment]
> Hi, I felt into the same issue. Found this info [https://jenkins.io/doc/pipeline/steps/aws-sam/](url) but the lack of examples keep me using the plugin with a Freestyle project

Hi I am trying to use this plugin with a Freestyle project but I am getting error while listing AWS regions. Did you face such issue?

**Comment by yuri1969** [comment]
I don't know if it helps but every Pipeline/Multibranch Pipeline project contains a :question: **Pipeline Syntax** link in the left bar (URL is basically: _<jenkins_hostname:port>/job/<job_name>/pipeline-syntax/_).

There you can select the plugin (`samDeploy`) from available installed ones and generate a pipeline step snippet. It should help until the doc gets some proper examples.

@man-bohara As for the AWS Region listing, it seems to be covered by #10 and fixed by #11.

**Comment by man-bohara** [comment]
@yuri1969 Thanks. I will try this.

**Comment by hoffa** [comment]
As mentioned above, usage similar to the following should work:

```groovy 
samDeploy([credentialsId: 'jenkins_sandbox', region: 'us-east-1', s3Bucket: 'sam-jenkins-plugin', stackName: 'sam-jenkins-plugin', parameters: [[key: 'Username', value: 'Modest']], templateFile: 'template.yml'])
```
